export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
// dbz
export const FETCH_DBZ_REQUEST = "FETCH_DBZ_REQUEST";
export const FETCH_DBZ_SUCCESS = "FETCH_DBZ_SUCCESS";
export const FETCH_DBZ_FAILURE = "FETCH_DBZ_FAILURE";
